# Generated by Django 3.2.7 on 2022-04-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingSiteApp', '0003_item_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='satic/image/no_pic.png', upload_to='static/images'),
        ),
    ]
