# Generated by Django 3.2.7 on 2022-04-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingSiteApp', '0004_item_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='time_added',
            new_name='time_addeda',
        ),
    ]
