# Generated by Django 3.2.7 on 2022-04-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingSiteApp', '0005_rename_time_added_item_time_addeda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='time_addeda',
            new_name='time_added',
        ),
    ]
