# Generated by Django 3.2.7 on 2022-04-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingSiteApp', '0006_rename_time_addeda_item_time_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='static/templates/shoppingSiteApp/no_pic.png', upload_to='media'),
        ),
    ]
