# Generated by Django 3.2.7 on 2022-04-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingSiteApp', '0007_alter_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(default='media/no_pic.png', upload_to='media'),
        ),
    ]
